/**
 * @fileOverview Base de dados de categorias para o jogo Tile Takeover.
 * Contém uma lista de todas as categorias de trivia disponíveis.
 */

export const allCategories: string[] = [
  'Figuras Notáveis',
  'Realizadores Internacionais',
  'Frutas',
  'Eletrodomésticos e Utensílios',
  'Invenções',
  'Dispositivos Médicos',
  'Casamento',
  'Mamíferos',
  'Programas de TV',
  'Emblemas de Clubes Desportivos',
  'Topografia Estrangeira',
  'Padaria e Pastelaria',
  'Vencedores de Óscares',
  'Edifícios e Construções Icónicas',
  'Comediantes',
  'Cantores Portugueses',
  'Gaveta de Tralhas',
  'Vegetais',
  'Decoração de Interiores',
  'Desportos e Modalidades',
  'Plantas',
  'Obras de Arte Mundiais',
  'Lazer e Tempo Livre',
  'Bandeiras',
  'Operações Aritméticas',
  'Capas de Álbuns',
  'Equipamentos de Futebol',
  'Música Brasileira',
  'Tradições e Costumes Portugueses',
  'Insetos e Rastejantes',
  'Roupas e Acessórios',
  'Profissões',
  'Notas e Moedas',
  'Religião',
  'Atrações Turísticas Mundiais',
  'Políticos do Século XX',
  'Políticos Portugueses',
  'Lanches',
  'Equipamentos Desportivos',
  'Transportes',
  'Membros da Realeza',
  'Cinema a Preto e Branco',
  'Regresso às Aulas',
  'Inglês',
  'Líderes Mundiais',
  'Duplas Famosas',
  'Figuras Mitológicas',
  'Títulos de Filmes',
  'Casais Famosos',
  'Bebés e Crianças',
  'Festival da Canção',
  'Rappers',
  'Mecânica de Automóveis',
  'Futebolistas Estrangeiros',
  'Pássaros',
  'Praia',
  'Treinadores de Futebol',
  'Personagens de Cinema',
  'Escritores Portugueses',
  'Instrumentos Musicais',
  'Povos do Mundo',
  'Aperitivos',
  'Estrelas de Cinema e TV dos anos 80',
  'Jogos e Brinquedos',
  'Sobremesas e Doces',
  'Bandas',
  'Futebolistas Portugueses',
  'Atletas Olímpicos Portugueses',
  'Música Popular Portuguesa',
  'Mercearia',
  'Figuras Públicas Internacionais',
  'Radialistas e Animadores',
  'Especiarias e Condimentos',
  'Gastronomia Portuguesa',
  'Símbolos e Pictogramas',
  'Fotografias Históricas',
  'Ilhas e Arquipélagos',
  'Capitais do Mundo',
  'Animais Aquáticos',
  'Tecnologia e Jogos',
  'Ciclismo',
  'Jogadores de Basquetebol',
  'Flores',
  'Cantoras Internacionais',
  'Raças de Cães',
  'Material de Laboratório',
  'Atrizes',
  'Espanhol',
  'Música dos anos 80',
  'Jogadores de Ténis',
  'Tabela Periódica',
  'Estádios de Futebol',
  'Ferramentas e Bricolage',
  'Pratos Internacionais',
  'Corpo Humano',
  'Animais Famosos',
  'Espaço e Astronomia',
  'Eventos e Datas Comemorativas',
  'Monumentos Nacionais',
  'Cantores Internacionais',
];
